// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TinyGenerator.Data;

#nullable disable

namespace TinyGenerator.data.Migrations
{
    [DbContext(typeof(TinyGeneratorDbContext))]
    [Migration("20260114191015_AddTipoPlanningAndSeriesPlanning")]
    partial class AddTipoPlanningAndSeriesPlanning
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("TinyGenerator.Models.Agent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AllowedProfiles")
                        .HasColumnType("TEXT")
                        .HasColumnName("allowed_profiles");

                    b.Property<string>("Config")
                        .HasColumnType("TEXT")
                        .HasColumnName("config");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("ExecutionPlan")
                        .HasColumnType("TEXT")
                        .HasColumnName("execution_plan");

                    b.Property<string>("Instructions")
                        .HasColumnType("TEXT")
                        .HasColumnName("instructions");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<string>("JsonResponseFormat")
                        .HasColumnType("TEXT")
                        .HasColumnName("json_response_format");

                    b.Property<int?>("ModelId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("model_id");

                    b.Property<int?>("MultiStepTemplateId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("multi_step_template_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<int?>("NumPredict")
                        .HasColumnType("INTEGER")
                        .HasColumnName("num_predict");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER")
                        .HasColumnName("priority");

                    b.Property<string>("Prompt")
                        .HasColumnType("TEXT")
                        .HasColumnName("prompt");

                    b.Property<int?>("RepeatLastN")
                        .HasColumnType("INTEGER")
                        .HasColumnName("repeat_last_n");

                    b.Property<double?>("RepeatPenalty")
                        .HasColumnType("REAL")
                        .HasColumnName("repeat_penalty");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("role");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<string>("Skills")
                        .HasColumnType("TEXT")
                        .HasColumnName("skills");

                    b.Property<double?>("Temperature")
                        .HasColumnType("REAL")
                        .HasColumnName("temperature");

                    b.Property<int?>("TopK")
                        .HasColumnType("INTEGER")
                        .HasColumnName("top_k");

                    b.Property<double?>("TopP")
                        .HasColumnType("REAL")
                        .HasColumnName("top_p");

                    b.Property<string>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<int?>("VoiceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("voice_rowid");

                    b.HasKey("Id");

                    b.ToTable("agents");
                });

            modelBuilder.Entity("TinyGenerator.Models.AppEventDefinition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enabled");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("event_type");

                    b.Property<bool>("Logged")
                        .HasColumnType("INTEGER")
                        .HasColumnName("logged");

                    b.Property<bool>("Notified")
                        .HasColumnType("INTEGER")
                        .HasColumnName("notified");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("app_events");
                });

            modelBuilder.Entity("TinyGenerator.Models.Chapter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChapterNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("chapter_number");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content");

                    b.Property<string>("MemoryKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("memory_key");

                    b.Property<string>("Ts")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ts");

                    b.HasKey("Id");

                    b.ToTable("chapters");
                });

            modelBuilder.Entity("TinyGenerator.Models.ChunkFacts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("ChunkNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("chunk_number");

                    b.Property<string>("FactsJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("facts_json");

                    b.Property<int>("StoryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("story_id");

                    b.Property<string>("Ts")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ts");

                    b.HasKey("Id");

                    b.ToTable("chunk_facts");
                });

            modelBuilder.Entity("TinyGenerator.Models.CoherenceScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("ChunkNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("chunk_number");

                    b.Property<string>("Errors")
                        .HasColumnType("TEXT")
                        .HasColumnName("errors");

                    b.Property<double>("GlobalCoherence")
                        .HasColumnType("REAL")
                        .HasColumnName("global_coherence");

                    b.Property<double>("LocalCoherence")
                        .HasColumnType("REAL")
                        .HasColumnName("local_coherence");

                    b.Property<int>("StoryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("story_id");

                    b.Property<string>("Ts")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ts");

                    b.HasKey("Id");

                    b.ToTable("coherence_scores");
                });

            modelBuilder.Entity("TinyGenerator.Models.ConsequenceImpact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("ConsequenceRuleId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("consequence_rule_id");

                    b.Property<int>("DeltaValue")
                        .HasColumnType("INTEGER")
                        .HasColumnName("delta_value");

                    b.Property<string>("ResourceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("resource_name");

                    b.HasKey("Id");

                    b.HasIndex("ConsequenceRuleId");

                    b.ToTable("consequence_impacts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConsequenceRuleId = 1,
                            DeltaValue = -10,
                            ResourceName = "Uomini"
                        },
                        new
                        {
                            Id = 2,
                            ConsequenceRuleId = 2,
                            DeltaValue = -15,
                            ResourceName = "Integrità"
                        });
                });

            modelBuilder.Entity("TinyGenerator.Models.ConsequenceRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<int>("NarrativeProfileId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("narrative_profile_id");

                    b.HasKey("Id");

                    b.HasIndex("NarrativeProfileId");

                    b.ToTable("consequence_rules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Perdita di uomini",
                            NarrativeProfileId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Danni strutturali",
                            NarrativeProfileId = 1
                        });
                });

            modelBuilder.Entity("TinyGenerator.Models.FailureRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<int>("NarrativeProfileId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("narrative_profile_id");

                    b.Property<string>("TriggerType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("trigger_type");

                    b.HasKey("Id");

                    b.HasIndex("NarrativeProfileId");

                    b.ToTable("failure_rules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Decisione affrettata sotto pressione",
                            NarrativeProfileId = 1,
                            TriggerType = "RandomUnderPressure"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Risorsa critica sotto soglia",
                            NarrativeProfileId = 1,
                            TriggerType = "ResourceBelowThreshold"
                        });
                });

            modelBuilder.Entity("TinyGenerator.Models.GlobalCoherence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("ChunkCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("chunk_count");

                    b.Property<double>("GlobalCoherenceValue")
                        .HasColumnType("REAL")
                        .HasColumnName("global_coherence_value");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<int>("StoryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("story_id");

                    b.Property<string>("Ts")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ts");

                    b.HasKey("Id");

                    b.ToTable("global_coherence");
                });

            modelBuilder.Entity("TinyGenerator.Models.LogAnalysis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("model_id");

                    b.Property<string>("RunScope")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("run_scope");

                    b.Property<bool>("Succeeded")
                        .HasColumnType("INTEGER")
                        .HasColumnName("succeeded");

                    b.Property<string>("ThreadId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("threadId");

                    b.HasKey("Id");

                    b.ToTable("log_analysis");
                });

            modelBuilder.Entity("TinyGenerator.Models.LogEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<string>("AgentName")
                        .HasColumnType("TEXT")
                        .HasColumnName("AgentName");

                    b.Property<bool>("Analized")
                        .HasColumnType("INTEGER")
                        .HasColumnName("analized");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Category");

                    b.Property<string>("ChatText")
                        .HasColumnType("TEXT")
                        .HasColumnName("chat_text");

                    b.Property<string>("Context")
                        .HasColumnType("TEXT")
                        .HasColumnName("Context");

                    b.Property<string>("Exception")
                        .HasColumnType("TEXT")
                        .HasColumnName("Exception");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Level");

                    b.Property<int?>("MaxStep")
                        .HasColumnType("INTEGER")
                        .HasColumnName("MaxStep");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Message");

                    b.Property<string>("Result")
                        .HasColumnType("TEXT")
                        .HasColumnName("Result");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<string>("State")
                        .HasColumnType("TEXT")
                        .HasColumnName("State");

                    b.Property<int?>("StepNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("StepNumber");

                    b.Property<long?>("StoryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("story_id");

                    b.Property<int>("ThreadId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ThreadId");

                    b.Property<string>("ThreadScope")
                        .HasColumnType("TEXT")
                        .HasColumnName("ThreadScope");

                    b.Property<string>("Ts")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Ts");

                    b.HasKey("Id");

                    b.ToTable("Log");
                });

            modelBuilder.Entity("TinyGenerator.Models.MicroObjective", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<int>("Difficulty")
                        .HasColumnType("INTEGER")
                        .HasColumnName("difficulty");

                    b.Property<int>("NarrativeProfileId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("narrative_profile_id");

                    b.HasKey("Id");

                    b.HasIndex("NarrativeProfileId");

                    b.ToTable("micro_objectives");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "DEFEND",
                            Description = "Difendere un settore critico",
                            Difficulty = 2,
                            NarrativeProfileId = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "DELAY",
                            Description = "Guadagnare tempo sotto pressione",
                            Difficulty = 3,
                            NarrativeProfileId = 1
                        });
                });

            modelBuilder.Entity("TinyGenerator.Models.ModelInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AmbientScore")
                        .HasColumnType("REAL");

                    b.Property<double>("BaseScore")
                        .HasColumnType("REAL");

                    b.Property<int>("ContextToUse")
                        .HasColumnType("INTEGER");

                    b.Property<double>("CostInPerToken")
                        .HasColumnType("REAL");

                    b.Property<double>("CostOutPerToken")
                        .HasColumnType("REAL");

                    b.Property<string>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Endpoint")
                        .HasColumnType("TEXT");

                    b.Property<int>("FunctionCallingScore")
                        .HasColumnType("INTEGER");

                    b.Property<double>("FxScore")
                        .HasColumnType("REAL");

                    b.Property<int>("InstructionFollowingScore")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLocal")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsNarrativeCompatible")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastMusicTestFile")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastResults_BaseJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastResults_MusicJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastResults_TtsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastResults_WriteJson")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastScore_Base")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LastScore_Music")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LastScore_Tts")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LastScore_Write")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastSoundTestFile")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastTestResults")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastTtsTestFile")
                        .HasColumnType("TEXT");

                    b.Property<long>("LimitTokensDay")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LimitTokensMonth")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LimitTokensWeek")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxContext")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxContextTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("MusicScore")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("NoTools")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<int?>("Speed")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("TestDurationSeconds")
                        .HasColumnType("REAL");

                    b.Property<double>("TextEvalScore")
                        .HasColumnType("REAL");

                    b.Property<double>("TotalScore")
                        .HasColumnType("REAL");

                    b.Property<double>("TtsScore")
                        .HasColumnType("REAL");

                    b.Property<string>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("WriterScore")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("models");
                });

            modelBuilder.Entity("TinyGenerator.Models.ModelTestAsset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<double?>("DurationSec")
                        .HasColumnType("REAL")
                        .HasColumnName("duration_sec");

                    b.Property<string>("FilePath")
                        .HasColumnType("TEXT")
                        .HasColumnName("file_path");

                    b.Property<string>("FileType")
                        .HasColumnType("TEXT")
                        .HasColumnName("file_type");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("size_bytes");

                    b.Property<int>("StepId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("step_id");

                    b.Property<long?>("StoryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("story_id");

                    b.HasKey("Id");

                    b.ToTable("model_test_assets");
                });

            modelBuilder.Entity("TinyGenerator.Models.ModelTestRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("duration_ms");

                    b.Property<int>("ModelId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("model_id");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<bool>("Passed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("passed");

                    b.Property<string>("RunDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("run_date");

                    b.Property<string>("TestFolder")
                        .HasColumnType("TEXT")
                        .HasColumnName("test_folder");

                    b.Property<string>("TestGroup")
                        .HasColumnType("TEXT")
                        .HasColumnName("test_group");

                    b.HasKey("Id");

                    b.ToTable("model_test_runs");
                });

            modelBuilder.Entity("TinyGenerator.Models.ModelTestStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("duration_ms");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT")
                        .HasColumnName("error");

                    b.Property<string>("InputJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("input_json");

                    b.Property<string>("OutputJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("output_json");

                    b.Property<bool>("Passed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("passed");

                    b.Property<int>("RunId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("run_id");

                    b.Property<string>("StepName")
                        .HasColumnType("TEXT")
                        .HasColumnName("step_name");

                    b.Property<int>("StepNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("step_number");

                    b.HasKey("Id");

                    b.ToTable("model_test_steps");
                });

            modelBuilder.Entity("TinyGenerator.Models.NarrativeProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("BaseSystemPrompt")
                        .HasColumnType("TEXT")
                        .HasColumnName("base_system_prompt");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("PovListJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("pov_list_json");

                    b.Property<string>("StylePrompt")
                        .HasColumnType("TEXT")
                        .HasColumnName("style_prompt");

                    b.HasKey("Id");

                    b.ToTable("narrative_profiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseSystemPrompt = "Scrivi narrativa a chunk continuo senza conclusioni.",
                            Description = "Conflitto armato ad alta tensione",
                            Name = "SciFi Militare",
                            StylePrompt = "Tono tecnico, militare, concreto."
                        });
                });

            modelBuilder.Entity("TinyGenerator.Models.NarrativeResource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("InitialValue")
                        .HasColumnType("INTEGER")
                        .HasColumnName("initial_value");

                    b.Property<int>("MaxValue")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_value");

                    b.Property<int>("MinValue")
                        .HasColumnType("INTEGER")
                        .HasColumnName("min_value");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("NarrativeProfileId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("narrative_profile_id");

                    b.HasKey("Id");

                    b.HasIndex("NarrativeProfileId");

                    b.ToTable("narrative_resources");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InitialValue = 100,
                            MaxValue = 100,
                            MinValue = 0,
                            Name = "Energia",
                            NarrativeProfileId = 1
                        },
                        new
                        {
                            Id = 2,
                            InitialValue = 100,
                            MaxValue = 100,
                            MinValue = 0,
                            Name = "Integrità",
                            NarrativeProfileId = 1
                        },
                        new
                        {
                            Id = 3,
                            InitialValue = 100,
                            MaxValue = 100,
                            MinValue = 0,
                            Name = "Uomini",
                            NarrativeProfileId = 1
                        });
                });

            modelBuilder.Entity("TinyGenerator.Models.PlannerMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int?>("BeatCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("beat_count");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("category");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<string>("PlannerPrompt")
                        .HasColumnType("TEXT")
                        .HasColumnName("planner_prompt");

                    b.Property<string>("RecommendedGenres")
                        .HasColumnType("TEXT")
                        .HasColumnName("recommended_genres");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB")
                        .HasColumnName("RowVersion");

                    b.Property<string>("Strengths")
                        .HasColumnType("TEXT")
                        .HasColumnName("strengths");

                    b.Property<string>("StructureSchema")
                        .HasColumnType("TEXT")
                        .HasColumnName("structure_schema");

                    b.Property<bool>("SupportsSeries")
                        .HasColumnType("INTEGER")
                        .HasColumnName("supports_series");

                    b.Property<string>("ValidationRules")
                        .HasColumnType("TEXT")
                        .HasColumnName("validation_rules");

                    b.Property<string>("Weaknesses")
                        .HasColumnType("TEXT")
                        .HasColumnName("weaknesses");

                    b.HasKey("Id");

                    b.ToTable("planner_methods");
                });

            modelBuilder.Entity("TinyGenerator.Models.Series", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AmbientazioneBase")
                        .HasColumnType("TEXT")
                        .HasColumnName("ambientazione_base");

                    b.Property<string>("ArcoNarrativoSerie")
                        .HasColumnType("TEXT")
                        .HasColumnName("arco_narrativo_serie");

                    b.Property<DateTime>("DataInserimento")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_inserimento");

                    b.Property<int?>("DefaultNarrativeProfileId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("default_narrative_profile_id");

                    b.Property<string>("DefaultPlannerMode")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("default_planner_mode");

                    b.Property<int?>("DefaultTipoPlanningId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("default_tipo_planning_id");

                    b.Property<int>("EpisodiGenerati")
                        .HasColumnType("INTEGER")
                        .HasColumnName("episodi_generati");

                    b.Property<string>("Folder")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("folder");

                    b.Property<string>("Genere")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("genere");

                    b.Property<string>("ImagesStyle")
                        .HasColumnType("TEXT")
                        .HasColumnName("images_style");

                    b.Property<string>("Lingua")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("lingua");

                    b.Property<int>("NarrativeConsistencyLevel")
                        .HasColumnType("INTEGER")
                        .HasColumnName("narrative_consistency_level");

                    b.Property<string>("NoteAI")
                        .HasColumnType("TEXT")
                        .HasColumnName("note_ai");

                    b.Property<string>("PeriodoNarrativo")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("periodo_narrativo");

                    b.Property<int?>("PlannerMethodId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("planner_method_id");

                    b.Property<string>("PremessaSerie")
                        .HasColumnType("TEXT")
                        .HasColumnName("premessa_serie");

                    b.Property<string>("RegoleNarrative")
                        .HasColumnType("TEXT")
                        .HasColumnName("regole_narrative");

                    b.Property<string>("Sottogenere")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("sottogenere");

                    b.Property<string>("StileScrittura")
                        .HasColumnType("TEXT")
                        .HasColumnName("stile_scrittura");

                    b.Property<string>("Target")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("target");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB")
                        .HasColumnName("timestamp");

                    b.Property<string>("Titolo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("titolo");

                    b.Property<string>("TonoBase")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("tono_base");

                    b.HasKey("Id");

                    b.HasIndex("DefaultTipoPlanningId");

                    b.HasIndex("PlannerMethodId");

                    b.ToTable("series");
                });

            modelBuilder.Entity("TinyGenerator.Models.SeriesCharacter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Aspect")
                        .HasColumnType("TEXT")
                        .HasColumnName("aspect");

                    b.Property<string>("ConflittoInterno")
                        .HasColumnType("TEXT")
                        .HasColumnName("conflitto_interno");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<int?>("EpisodeIn")
                        .HasColumnType("INTEGER")
                        .HasColumnName("episode_in");

                    b.Property<int?>("EpisodeOut")
                        .HasColumnType("INTEGER")
                        .HasColumnName("episode_out");

                    b.Property<string>("Eta")
                        .HasColumnType("TEXT")
                        .HasColumnName("eta");

                    b.Property<string>("Formazione")
                        .HasColumnType("TEXT")
                        .HasColumnName("formazione");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("gender");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT")
                        .HasColumnName("image");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Profilo")
                        .HasColumnType("TEXT")
                        .HasColumnName("profilo");

                    b.Property<int>("SerieId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("serie_id");

                    b.Property<string>("Specializzazione")
                        .HasColumnType("TEXT")
                        .HasColumnName("specializzazione");

                    b.Property<int?>("VoiceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("voice_id");

                    b.HasKey("Id");

                    b.HasIndex("SerieId");

                    b.ToTable("series_characters");
                });

            modelBuilder.Entity("TinyGenerator.Models.SeriesEpisode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER")
                        .HasColumnName("number");

                    b.Property<int>("SerieId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("serie_id");

                    b.Property<int?>("TipoPlanningId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tipo_planning_id");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<string>("Trama")
                        .HasColumnType("TEXT")
                        .HasColumnName("trama");

                    b.HasKey("Id");

                    b.HasIndex("SerieId");

                    b.HasIndex("TipoPlanningId");

                    b.ToTable("series_episodes");
                });

            modelBuilder.Entity("TinyGenerator.Models.StepTemplate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int?>("CharactersStep")
                        .HasColumnType("INTEGER")
                        .HasColumnName("characters_step");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("EvaluationSteps")
                        .HasColumnType("TEXT")
                        .HasColumnName("evaluation_steps");

                    b.Property<int?>("FullStoryStep")
                        .HasColumnType("INTEGER")
                        .HasColumnName("full_story_step");

                    b.Property<string>("Instructions")
                        .HasColumnType("TEXT")
                        .HasColumnName("instructions");

                    b.Property<int?>("MinCharsStory")
                        .HasColumnType("INTEGER")
                        .HasColumnName("min_chars_story");

                    b.Property<int?>("MinCharsTrama")
                        .HasColumnType("INTEGER")
                        .HasColumnName("min_chars_trama");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<string>("StepPrompt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("step_prompt");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("task_type");

                    b.Property<string>("TramaSteps")
                        .HasColumnType("TEXT")
                        .HasColumnName("trama_steps");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("step_templates");
                });

            modelBuilder.Entity("TinyGenerator.Models.StoryEvaluation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("ActionDefects")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("action_defects");

                    b.Property<int>("ActionScore")
                        .HasColumnType("INTEGER")
                        .HasColumnName("action_score");

                    b.Property<int?>("AgentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("agent_id");

                    b.Property<string>("EmotionalImpactDefects")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("emotional_impact_defects");

                    b.Property<int>("EmotionalImpactScore")
                        .HasColumnType("INTEGER")
                        .HasColumnName("emotional_impact_score");

                    b.Property<long?>("ModelId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("model_id");

                    b.Property<string>("NarrativeCoherenceDefects")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("narrative_coherence_defects");

                    b.Property<int>("NarrativeCoherenceScore")
                        .HasColumnType("INTEGER")
                        .HasColumnName("narrative_coherence_score");

                    b.Property<string>("OriginalityDefects")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("originality_defects");

                    b.Property<int>("OriginalityScore")
                        .HasColumnType("INTEGER")
                        .HasColumnName("originality_score");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("raw_json");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<long>("StoryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("story_id");

                    b.Property<string>("Timestamp")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ts");

                    b.Property<double>("TotalScore")
                        .HasColumnType("REAL")
                        .HasColumnName("total_score");

                    b.HasKey("Id");

                    b.ToTable("stories_evaluations");
                });

            modelBuilder.Entity("TinyGenerator.Models.StoryRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int?>("AgentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("agent_id");

                    b.Property<bool>("Approved")
                        .HasColumnType("INTEGER")
                        .HasColumnName("approved");

                    b.Property<int>("CharCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("char_count");

                    b.Property<string>("Characters")
                        .HasColumnType("TEXT")
                        .HasColumnName("characters");

                    b.Property<string>("Eval")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("eval");

                    b.Property<string>("Folder")
                        .HasColumnType("TEXT")
                        .HasColumnName("folder");

                    b.Property<int?>("FormatterModelId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("formatter_model");

                    b.Property<string>("FormatterPromptHash")
                        .HasColumnType("TEXT")
                        .HasColumnName("formatter_prompt_hash");

                    b.Property<bool>("GeneratedAmbient")
                        .HasColumnType("INTEGER")
                        .HasColumnName("generated_ambient");

                    b.Property<bool>("GeneratedEffects")
                        .HasColumnType("INTEGER")
                        .HasColumnName("generated_effects");

                    b.Property<bool>("GeneratedMixedAudio")
                        .HasColumnType("INTEGER")
                        .HasColumnName("generated_mixed_audio");

                    b.Property<bool>("GeneratedMusic")
                        .HasColumnType("INTEGER")
                        .HasColumnName("generated_music");

                    b.Property<bool>("GeneratedTts")
                        .HasColumnType("INTEGER")
                        .HasColumnName("generated_tts");

                    b.Property<bool>("GeneratedTtsJson")
                        .HasColumnType("INTEGER")
                        .HasColumnName("generated_tts_json");

                    b.Property<string>("GenerationId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("generation_id");

                    b.Property<string>("MemoryKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("memory_key");

                    b.Property<int?>("ModelId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("model_id");

                    b.Property<string>("NarrativeEngineStatus")
                        .HasColumnType("TEXT")
                        .HasColumnName("narrative_status");

                    b.Property<int?>("NarrativeProfileId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("narrative_profile_id");

                    b.Property<string>("PlannerMode")
                        .HasColumnType("TEXT")
                        .HasColumnName("planner_mode");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("prompt");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<long?>("RuntimeStateId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("runtime_state_id");

                    b.Property<double>("Score")
                        .HasColumnType("REAL")
                        .HasColumnName("score");

                    b.Property<int?>("SerieEpisode")
                        .HasColumnType("INTEGER")
                        .HasColumnName("serie_episode");

                    b.Property<int?>("SerieId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("serie_id");

                    b.Property<int?>("StatusId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status_id");

                    b.Property<long?>("StoryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("story_id");

                    b.Property<string>("StoryRaw")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("story_raw");

                    b.Property<string>("StoryRevised")
                        .HasColumnType("TEXT")
                        .HasColumnName("story_revised");

                    b.Property<string>("StoryStructure")
                        .HasColumnType("TEXT")
                        .HasColumnName("story_structure");

                    b.Property<string>("StoryTagged")
                        .HasColumnType("TEXT")
                        .HasColumnName("story_tagged");

                    b.Property<int?>("StoryTaggedVersion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("story_tagged_version");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT")
                        .HasColumnName("summary");

                    b.Property<string>("Timestamp")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ts");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("stories");
                });

            modelBuilder.Entity("TinyGenerator.Models.StoryResourceState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("CurrentValue")
                        .HasColumnType("INTEGER")
                        .HasColumnName("current_value");

                    b.Property<string>("ResourceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("resource_name");

                    b.Property<long>("StoryRuntimeStateId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("story_runtime_state_id");

                    b.HasKey("Id");

                    b.HasIndex("StoryRuntimeStateId");

                    b.ToTable("story_resource_states");
                });

            modelBuilder.Entity("TinyGenerator.Models.StoryRuntimeState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("CurrentChunkIndex")
                        .HasColumnType("INTEGER")
                        .HasColumnName("current_chunk_index");

                    b.Property<string>("CurrentPOV")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("current_pov");

                    b.Property<string>("CurrentPhase")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("current_phase");

                    b.Property<int>("FailureCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("failure_count");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<string>("LastContext")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("last_context");

                    b.Property<int>("NarrativeProfileId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("narrative_profile_id");

                    b.Property<long>("StoryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("story_id");

                    b.HasKey("Id");

                    b.HasIndex("NarrativeProfileId");

                    b.HasIndex("StoryId");

                    b.ToTable("story_runtime_states");
                });

            modelBuilder.Entity("TinyGenerator.Models.StoryStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AgentType")
                        .HasColumnType("TEXT")
                        .HasColumnName("agent_type");

                    b.Property<string>("CaptionToExecute")
                        .HasColumnType("TEXT")
                        .HasColumnName("caption_to_execute");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT")
                        .HasColumnName("color");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("FunctionName")
                        .HasColumnType("TEXT")
                        .HasColumnName("function_name");

                    b.Property<string>("OperationType")
                        .HasColumnType("TEXT")
                        .HasColumnName("operation_type");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<int>("Step")
                        .HasColumnType("INTEGER")
                        .HasColumnName("step");

                    b.HasKey("Id");

                    b.ToTable("stories_status");
                });

            modelBuilder.Entity("TinyGenerator.Models.TaskExecution", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int?>("CheckerAgentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("checker_agent_id");

                    b.Property<string>("Config")
                        .HasColumnType("TEXT")
                        .HasColumnName("config");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentStep")
                        .HasColumnType("INTEGER")
                        .HasColumnName("current_step");

                    b.Property<long?>("EntityId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("entity_id");

                    b.Property<int?>("ExecutorAgentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("executor_agent_id");

                    b.Property<string>("InitialContext")
                        .HasColumnType("TEXT")
                        .HasColumnName("initial_context");

                    b.Property<int>("MaxStep")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_step");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("retry_count");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("StepPrompt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("step_prompt");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("task_type");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("task_executions");
                });

            modelBuilder.Entity("TinyGenerator.Models.TaskExecutionStep", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("attempt_count");

                    b.Property<string>("CompletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("completed_at");

                    b.Property<long>("ExecutionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("execution_id");

                    b.Property<string>("StartedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at");

                    b.Property<string>("StepInstruction")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("step_instruction");

                    b.Property<int>("StepNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("step_number");

                    b.Property<string>("StepOutput")
                        .HasColumnType("TEXT")
                        .HasColumnName("step_output");

                    b.Property<string>("ValidationResultJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("validation_result");

                    b.HasKey("Id");

                    b.ToTable("task_execution_steps");
                });

            modelBuilder.Entity("TinyGenerator.Models.TaskTypeInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<string>("DefaultCheckerRole")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("default_checker_role");

                    b.Property<string>("DefaultExecutorRole")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("default_executor_role");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("OutputMergeStrategy")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("output_merge_strategy");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<string>("ValidationCriteria")
                        .HasColumnType("TEXT")
                        .HasColumnName("validation_criteria");

                    b.HasKey("Id");

                    b.ToTable("task_types");
                });

            modelBuilder.Entity("TinyGenerator.Models.TestDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER")
                        .HasColumnName("active");

                    b.Property<string>("AllowedPlugins")
                        .HasColumnType("TEXT")
                        .HasColumnName("allowed_plugins");

                    b.Property<string>("ExecutionPlan")
                        .HasColumnType("TEXT")
                        .HasColumnName("execution_plan");

                    b.Property<string>("ExpectedAsset")
                        .HasColumnType("TEXT")
                        .HasColumnName("expected_asset");

                    b.Property<string>("ExpectedBehavior")
                        .HasColumnType("TEXT")
                        .HasColumnName("expected_behavior");

                    b.Property<string>("ExpectedPromptValue")
                        .HasColumnType("TEXT")
                        .HasColumnName("expected_prompt_value");

                    b.Property<string>("FilesToCopy")
                        .HasColumnType("TEXT")
                        .HasColumnName("files_to_copy");

                    b.Property<string>("FunctionName")
                        .HasColumnType("TEXT")
                        .HasColumnName("function_name");

                    b.Property<string>("GroupName")
                        .HasColumnType("TEXT")
                        .HasColumnName("test_group");

                    b.Property<string>("JsonResponseFormat")
                        .HasColumnType("TEXT")
                        .HasColumnName("json_response_format");

                    b.Property<string>("Library")
                        .HasColumnType("TEXT")
                        .HasColumnName("library");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER")
                        .HasColumnName("priority");

                    b.Property<string>("Prompt")
                        .HasColumnType("TEXT")
                        .HasColumnName("prompt");

                    b.Property<double?>("Temperature")
                        .HasColumnType("REAL")
                        .HasColumnName("temperature");

                    b.Property<string>("TestType")
                        .HasColumnType("TEXT")
                        .HasColumnName("test_type");

                    b.Property<int>("TimeoutSecs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("timeout_secs");

                    b.Property<double?>("TopP")
                        .HasColumnType("REAL")
                        .HasColumnName("top_p");

                    b.Property<string>("ValidScoreRange")
                        .HasColumnType("TEXT")
                        .HasColumnName("valid_score_range");

                    b.HasKey("Id");

                    b.ToTable("test_definitions");
                });

            modelBuilder.Entity("TinyGenerator.Models.TestPrompt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER")
                        .HasColumnName("active");

                    b.Property<string>("GroupName")
                        .HasColumnType("TEXT")
                        .HasColumnName("group_name");

                    b.Property<string>("Library")
                        .HasColumnType("TEXT")
                        .HasColumnName("library");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER")
                        .HasColumnName("priority");

                    b.Property<string>("Prompt")
                        .HasColumnType("TEXT")
                        .HasColumnName("prompt");

                    b.HasKey("Id");

                    b.ToTable("test_prompts");
                });

            modelBuilder.Entity("TinyGenerator.Models.TipoPlanning", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_tipo_planning");

                    b.Property<string>("Codice")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("codice");

                    b.Property<string>("Descrizione")
                        .HasColumnType("TEXT")
                        .HasColumnName("descrizione");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("nome");

                    b.Property<string>("SuccessioneStati")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("successione_stati");

                    b.HasKey("Id");

                    b.HasIndex("Codice")
                        .IsUnique();

                    b.ToTable("tipo_planning");
                });

            modelBuilder.Entity("TinyGenerator.Models.TtsVoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Age")
                        .HasColumnType("TEXT")
                        .HasColumnName("age");

                    b.Property<string>("Archetype")
                        .HasColumnType("TEXT")
                        .HasColumnName("archetype");

                    b.Property<double?>("Confidence")
                        .HasColumnType("REAL")
                        .HasColumnName("confidence");

                    b.Property<string>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<bool>("Disabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("disabled");

                    b.Property<string>("Gender")
                        .HasColumnType("TEXT")
                        .HasColumnName("gender");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT")
                        .HasColumnName("language");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT")
                        .HasColumnName("model");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<double?>("Score")
                        .HasColumnType("REAL")
                        .HasColumnName("score");

                    b.Property<string>("Tags")
                        .HasColumnType("TEXT")
                        .HasColumnName("tags");

                    b.Property<string>("TemplateWav")
                        .HasColumnType("TEXT")
                        .HasColumnName("template_wav");

                    b.Property<string>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("VoiceId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("voice_id");

                    b.HasKey("Id");

                    b.ToTable("tts_voices");
                });

            modelBuilder.Entity("TinyGenerator.Models.UsageState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CostThisMonth")
                        .HasColumnType("REAL")
                        .HasColumnName("cost_this_month");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("month");

                    b.Property<long>("TokensThisMonth")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tokens_this_month");

                    b.Property<long>("TokensThisRun")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tokens_this_run");

                    b.HasKey("Id");

                    b.ToTable("usage_state");
                });

            modelBuilder.Entity("TinyGenerator.Models.ConsequenceImpact", b =>
                {
                    b.HasOne("TinyGenerator.Models.ConsequenceRule", "ConsequenceRule")
                        .WithMany("Impacts")
                        .HasForeignKey("ConsequenceRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConsequenceRule");
                });

            modelBuilder.Entity("TinyGenerator.Models.ConsequenceRule", b =>
                {
                    b.HasOne("TinyGenerator.Models.NarrativeProfile", "NarrativeProfile")
                        .WithMany("ConsequenceRules")
                        .HasForeignKey("NarrativeProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NarrativeProfile");
                });

            modelBuilder.Entity("TinyGenerator.Models.FailureRule", b =>
                {
                    b.HasOne("TinyGenerator.Models.NarrativeProfile", "NarrativeProfile")
                        .WithMany("FailureRules")
                        .HasForeignKey("NarrativeProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NarrativeProfile");
                });

            modelBuilder.Entity("TinyGenerator.Models.MicroObjective", b =>
                {
                    b.HasOne("TinyGenerator.Models.NarrativeProfile", "NarrativeProfile")
                        .WithMany("MicroObjectives")
                        .HasForeignKey("NarrativeProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NarrativeProfile");
                });

            modelBuilder.Entity("TinyGenerator.Models.NarrativeResource", b =>
                {
                    b.HasOne("TinyGenerator.Models.NarrativeProfile", "NarrativeProfile")
                        .WithMany("Resources")
                        .HasForeignKey("NarrativeProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NarrativeProfile");
                });

            modelBuilder.Entity("TinyGenerator.Models.Series", b =>
                {
                    b.HasOne("TinyGenerator.Models.TipoPlanning", null)
                        .WithMany()
                        .HasForeignKey("DefaultTipoPlanningId");

                    b.HasOne("TinyGenerator.Models.PlannerMethod", null)
                        .WithMany()
                        .HasForeignKey("PlannerMethodId");
                });

            modelBuilder.Entity("TinyGenerator.Models.SeriesCharacter", b =>
                {
                    b.HasOne("TinyGenerator.Models.Series", null)
                        .WithMany("Characters")
                        .HasForeignKey("SerieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TinyGenerator.Models.SeriesEpisode", b =>
                {
                    b.HasOne("TinyGenerator.Models.Series", null)
                        .WithMany("Episodes")
                        .HasForeignKey("SerieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TinyGenerator.Models.TipoPlanning", null)
                        .WithMany()
                        .HasForeignKey("TipoPlanningId");
                });

            modelBuilder.Entity("TinyGenerator.Models.StoryResourceState", b =>
                {
                    b.HasOne("TinyGenerator.Models.StoryRuntimeState", "StoryRuntimeState")
                        .WithMany()
                        .HasForeignKey("StoryRuntimeStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StoryRuntimeState");
                });

            modelBuilder.Entity("TinyGenerator.Models.StoryRuntimeState", b =>
                {
                    b.HasOne("TinyGenerator.Models.NarrativeProfile", "NarrativeProfile")
                        .WithMany()
                        .HasForeignKey("NarrativeProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TinyGenerator.Models.StoryRecord", "Story")
                        .WithMany()
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NarrativeProfile");

                    b.Navigation("Story");
                });

            modelBuilder.Entity("TinyGenerator.Models.ConsequenceRule", b =>
                {
                    b.Navigation("Impacts");
                });

            modelBuilder.Entity("TinyGenerator.Models.NarrativeProfile", b =>
                {
                    b.Navigation("ConsequenceRules");

                    b.Navigation("FailureRules");

                    b.Navigation("MicroObjectives");

                    b.Navigation("Resources");
                });

            modelBuilder.Entity("TinyGenerator.Models.Series", b =>
                {
                    b.Navigation("Characters");

                    b.Navigation("Episodes");
                });
#pragma warning restore 612, 618
        }
    }
}
