// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TinyGenerator.Data;

#nullable disable

namespace TinyGenerator.Data.Migrations
{
    [DbContext(typeof(TinyGeneratorDbContext))]
    [Migration("20260101210000_AddSeriesCharacterDetails")]
    partial class AddSeriesCharacterDetails
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            // Full model snapshot would go here
            // This is generated by the migration infrastructure
#pragma warning restore 612, 618
        }
    }
}
