// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TinyGenerator.Data;

#nullable disable

namespace TinyGenerator.Data.Migrations
{
    [DbContext(typeof(TinyGeneratorDbContext))]
    partial class TinyGeneratorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("TinyGenerator.Models.Agent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Config")
                        .HasColumnType("TEXT")
                        .HasColumnName("config");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("ExecutionPlan")
                        .HasColumnType("TEXT")
                        .HasColumnName("execution_plan");

                    b.Property<string>("Instructions")
                        .HasColumnType("TEXT")
                        .HasColumnName("instructions");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<string>("JsonResponseFormat")
                        .HasColumnType("TEXT")
                        .HasColumnName("json_response_format");

                    b.Property<int?>("ModelId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("model_id");

                    b.Property<int?>("MultiStepTemplateId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("multi_step_template_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<string>("Prompt")
                        .HasColumnType("TEXT")
                        .HasColumnName("prompt");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("role");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<string>("Skills")
                        .HasColumnType("TEXT")
                        .HasColumnName("skills");

                    b.Property<double?>("Temperature")
                        .HasColumnType("REAL")
                        .HasColumnName("temperature");

                    b.Property<double?>("TopP")
                        .HasColumnType("REAL")
                        .HasColumnName("top_p");

                    b.Property<string>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<int?>("VoiceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("voice_rowid");

                    b.HasKey("Id");

                    b.ToTable("agents");
                });

            modelBuilder.Entity("TinyGenerator.Models.LogEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<string>("AgentName")
                        .HasColumnType("TEXT")
                        .HasColumnName("AgentName");

                    b.Property<bool>("Analized")
                        .HasColumnType("INTEGER")
                        .HasColumnName("analized");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Category");

                    b.Property<string>("ChatText")
                        .HasColumnType("TEXT")
                        .HasColumnName("chat_text");

                    b.Property<string>("Context")
                        .HasColumnType("TEXT")
                        .HasColumnName("Context");

                    b.Property<string>("Exception")
                        .HasColumnType("TEXT")
                        .HasColumnName("Exception");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Level");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Message");

                    b.Property<string>("Result")
                        .HasColumnType("TEXT")
                        .HasColumnName("Result");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<string>("State")
                        .HasColumnType("TEXT")
                        .HasColumnName("State");

                    b.Property<int>("ThreadId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ThreadId");

                    b.Property<string>("ThreadScope")
                        .HasColumnType("TEXT")
                        .HasColumnName("ThreadScope");

                    b.Property<string>("Ts")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Ts");

                    b.HasKey("Id");

                    b.ToTable("Log");
                });

            modelBuilder.Entity("TinyGenerator.Models.ModelInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AmbientScore")
                        .HasColumnType("REAL");

                    b.Property<double>("BaseScore")
                        .HasColumnType("REAL");

                    b.Property<int>("ContextToUse")
                        .HasColumnType("INTEGER");

                    b.Property<double>("CostInPerToken")
                        .HasColumnType("REAL");

                    b.Property<double>("CostOutPerToken")
                        .HasColumnType("REAL");

                    b.Property<string>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Endpoint")
                        .HasColumnType("TEXT");

                    b.Property<int>("FunctionCallingScore")
                        .HasColumnType("INTEGER");

                    b.Property<double>("FxScore")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsLocal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastMusicTestFile")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastResults_BaseJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastResults_MusicJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastResults_TtsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastResults_WriteJson")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastScore_Base")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LastScore_Music")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LastScore_Tts")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LastScore_Write")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastSoundTestFile")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastTestResults")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastTtsTestFile")
                        .HasColumnType("TEXT");

                    b.Property<long>("LimitTokensDay")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LimitTokensMonth")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LimitTokensWeek")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxContext")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("MusicScore")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("NoTools")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<double?>("TestDurationSeconds")
                        .HasColumnType("REAL");

                    b.Property<double>("TextEvalScore")
                        .HasColumnType("REAL");

                    b.Property<double>("TotalScore")
                        .HasColumnType("REAL");

                    b.Property<double>("TtsScore")
                        .HasColumnType("REAL");

                    b.Property<string>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("WriterScore")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("models");
                });

            modelBuilder.Entity("TinyGenerator.Models.StepTemplate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Instructions")
                        .HasColumnType("TEXT")
                        .HasColumnName("instructions");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<string>("StepPrompt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("step_prompt");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("task_type");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("step_templates");
                });

            modelBuilder.Entity("TinyGenerator.Models.StoryEvaluation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("ActionDefects")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("action_defects");

                    b.Property<int>("ActionScore")
                        .HasColumnType("INTEGER")
                        .HasColumnName("action_score");

                    b.Property<int?>("AgentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("agent_id");

                    b.Property<string>("EmotionalImpactDefects")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("emotional_impact_defects");

                    b.Property<int>("EmotionalImpactScore")
                        .HasColumnType("INTEGER")
                        .HasColumnName("emotional_impact_score");

                    b.Property<long?>("ModelId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("model_id");

                    b.Property<string>("NarrativeCoherenceDefects")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("narrative_coherence_defects");

                    b.Property<int>("NarrativeCoherenceScore")
                        .HasColumnType("INTEGER")
                        .HasColumnName("narrative_coherence_score");

                    b.Property<string>("OriginalityDefects")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("originality_defects");

                    b.Property<int>("OriginalityScore")
                        .HasColumnType("INTEGER")
                        .HasColumnName("originality_score");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("raw_json");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<long>("StoryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("story_id");

                    b.Property<string>("Timestamp")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ts");

                    b.Property<double>("TotalScore")
                        .HasColumnType("REAL")
                        .HasColumnName("total_score");

                    b.HasKey("Id");

                    b.ToTable("stories_evaluations");
                });

            modelBuilder.Entity("TinyGenerator.Models.StoryRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int?>("AgentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("agent_id");

                    b.Property<bool>("Approved")
                        .HasColumnType("INTEGER")
                        .HasColumnName("approved");

                    b.Property<int>("CharCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("char_count");

                    b.Property<string>("Eval")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("eval");

                    b.Property<string>("Folder")
                        .HasColumnType("TEXT")
                        .HasColumnName("folder");

                    b.Property<string>("GenerationId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("generation_id");

                    b.Property<string>("MemoryKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("memory_key");

                    b.Property<int?>("ModelId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("model_id");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("prompt");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<double>("Score")
                        .HasColumnType("REAL")
                        .HasColumnName("score");

                    b.Property<int?>("StatusId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status_id");

                    b.Property<string>("Story")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("story");

                    b.Property<string>("Timestamp")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ts");

                    b.HasKey("Id");

                    b.ToTable("stories");
                });

            modelBuilder.Entity("TinyGenerator.Models.StoryStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AgentType")
                        .HasColumnType("TEXT")
                        .HasColumnName("agent_type");

                    b.Property<string>("CaptionToExecute")
                        .HasColumnType("TEXT")
                        .HasColumnName("caption_to_execute");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT")
                        .HasColumnName("color");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("FunctionName")
                        .HasColumnType("TEXT")
                        .HasColumnName("function_name");

                    b.Property<string>("OperationType")
                        .HasColumnType("TEXT")
                        .HasColumnName("operation_type");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<int>("Step")
                        .HasColumnType("INTEGER")
                        .HasColumnName("step");

                    b.HasKey("Id");

                    b.ToTable("stories_status");
                });

            modelBuilder.Entity("TinyGenerator.Models.TaskTypeInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<string>("DefaultCheckerRole")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("default_checker_role");

                    b.Property<string>("DefaultExecutorRole")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("default_executor_role");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("OutputMergeStrategy")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("output_merge_strategy");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<string>("ValidationCriteria")
                        .HasColumnType("TEXT")
                        .HasColumnName("validation_criteria");

                    b.HasKey("Id");

                    b.ToTable("task_types");
                });

            modelBuilder.Entity("TinyGenerator.Models.TestDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER")
                        .HasColumnName("active");

                    b.Property<string>("AllowedPlugins")
                        .HasColumnType("TEXT")
                        .HasColumnName("allowed_plugins");

                    b.Property<string>("ExecutionPlan")
                        .HasColumnType("TEXT")
                        .HasColumnName("execution_plan");

                    b.Property<string>("ExpectedAsset")
                        .HasColumnType("TEXT")
                        .HasColumnName("expected_asset");

                    b.Property<string>("ExpectedBehavior")
                        .HasColumnType("TEXT")
                        .HasColumnName("expected_behavior");

                    b.Property<string>("ExpectedPromptValue")
                        .HasColumnType("TEXT")
                        .HasColumnName("expected_prompt_value");

                    b.Property<string>("FilesToCopy")
                        .HasColumnType("TEXT")
                        .HasColumnName("files_to_copy");

                    b.Property<string>("FunctionName")
                        .HasColumnType("TEXT")
                        .HasColumnName("function_name");

                    b.Property<string>("GroupName")
                        .HasColumnType("TEXT")
                        .HasColumnName("test_group");

                    b.Property<string>("JsonResponseFormat")
                        .HasColumnType("TEXT")
                        .HasColumnName("json_response_format");

                    b.Property<string>("Library")
                        .HasColumnType("TEXT")
                        .HasColumnName("library");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER")
                        .HasColumnName("priority");

                    b.Property<string>("Prompt")
                        .HasColumnType("TEXT")
                        .HasColumnName("prompt");

                    b.Property<double?>("Temperature")
                        .HasColumnType("REAL")
                        .HasColumnName("temperature");

                    b.Property<string>("TestType")
                        .HasColumnType("TEXT")
                        .HasColumnName("test_type");

                    b.Property<int>("TimeoutSecs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("timeout_secs");

                    b.Property<double?>("TopP")
                        .HasColumnType("REAL")
                        .HasColumnName("top_p");

                    b.Property<string>("ValidScoreRange")
                        .HasColumnType("TEXT")
                        .HasColumnName("valid_score_range");

                    b.HasKey("Id");

                    b.ToTable("test_definitions");
                });

            modelBuilder.Entity("TinyGenerator.Models.TtsVoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Age")
                        .HasColumnType("TEXT")
                        .HasColumnName("age");

                    b.Property<string>("Archetype")
                        .HasColumnType("TEXT")
                        .HasColumnName("archetype");

                    b.Property<double?>("Confidence")
                        .HasColumnType("REAL")
                        .HasColumnName("confidence");

                    b.Property<string>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Gender")
                        .HasColumnType("TEXT")
                        .HasColumnName("gender");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT")
                        .HasColumnName("language");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT")
                        .HasColumnName("model");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<double?>("Score")
                        .HasColumnType("REAL")
                        .HasColumnName("score");

                    b.Property<string>("Tags")
                        .HasColumnType("TEXT")
                        .HasColumnName("tags");

                    b.Property<string>("TemplateWav")
                        .HasColumnType("TEXT")
                        .HasColumnName("template_wav");

                    b.Property<string>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("VoiceId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("voice_id");

                    b.HasKey("Id");

                    b.ToTable("tts_voices");
                });
#pragma warning restore 612, 618
        }
    }
}
