// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TinyGenerator.Data;

#nullable disable

namespace TinyGenerator.Data.Migrations
{
    [DbContext(typeof(TinyGeneratorDbContext))]
    partial class TinyGeneratorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("TinyGenerator.Models.Agent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Config")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecutionPlan")
                        .HasColumnType("TEXT");

                    b.Property<string>("Instructions")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JsonResponseFormat")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ModelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModelName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MultiStepTemplateId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Prompt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<string>("Skills")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Temperature")
                        .HasColumnType("REAL");

                    b.Property<double?>("TopP")
                        .HasColumnType("REAL");

                    b.Property<string>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("VoiceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("agents");
                });

            modelBuilder.Entity("TinyGenerator.Models.LogEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AgentName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Analized")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChatText")
                        .HasColumnType("TEXT");

                    b.Property<string>("Context")
                        .HasColumnType("TEXT");

                    b.Property<string>("Exception")
                        .HasColumnType("TEXT");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Result")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<string>("State")
                        .HasColumnType("TEXT");

                    b.Property<int>("ThreadId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ThreadScope")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ts")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Log");
                });

            modelBuilder.Entity("TinyGenerator.Models.ModelInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AmbientScore")
                        .HasColumnType("REAL");

                    b.Property<double>("BaseScore")
                        .HasColumnType("REAL");

                    b.Property<int>("ContextToUse")
                        .HasColumnType("INTEGER");

                    b.Property<double>("CostInPerToken")
                        .HasColumnType("REAL");

                    b.Property<double>("CostOutPerToken")
                        .HasColumnType("REAL");

                    b.Property<string>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Endpoint")
                        .HasColumnType("TEXT");

                    b.Property<int>("FunctionCallingScore")
                        .HasColumnType("INTEGER");

                    b.Property<double>("FxScore")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsLocal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastMusicTestFile")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastResults_BaseJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastResults_MusicJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastResults_TtsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastResults_WriteJson")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastScore_Base")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LastScore_Music")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LastScore_Tts")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LastScore_Write")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastSoundTestFile")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastTestResults")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastTtsTestFile")
                        .HasColumnType("TEXT");

                    b.Property<long>("LimitTokensDay")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LimitTokensMonth")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LimitTokensWeek")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxContext")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("MusicScore")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("NoTools")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<double?>("TestDurationSeconds")
                        .HasColumnType("REAL");

                    b.Property<double>("TextEvalScore")
                        .HasColumnType("REAL");

                    b.Property<double>("TotalScore")
                        .HasColumnType("REAL");

                    b.Property<double>("TtsScore")
                        .HasColumnType("REAL");

                    b.Property<string>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("WriterScore")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("models");
                });

            modelBuilder.Entity("TinyGenerator.Models.StepTemplate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Instructions")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<string>("StepPrompt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("step_templates");
                });

            modelBuilder.Entity("TinyGenerator.Models.StoryEvaluation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionDefects")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ActionScore")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AgentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AgentModel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmotionalImpactDefects")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EmotionalImpactScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("ModelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NarrativeCoherenceDefects")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NarrativeCoherenceScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginalityDefects")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OriginalityScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<long>("StoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Timestamp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("TotalScore")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("evaluations");
                });

            modelBuilder.Entity("TinyGenerator.Models.StoryRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Agent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Approved")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Eval")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Folder")
                        .HasColumnType("TEXT");

                    b.Property<string>("GenerationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasVoiceSource")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MemoryKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<double>("Score")
                        .HasColumnType("REAL");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StatusAgentType")
                        .HasColumnType("TEXT");

                    b.Property<string>("StatusColor")
                        .HasColumnType("TEXT");

                    b.Property<string>("StatusDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("StatusFunctionName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("StatusId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StatusOperationType")
                        .HasColumnType("TEXT");

                    b.Property<int?>("StatusStep")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Story")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TestRunId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TestStepId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Timestamp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("stories");
                });

            modelBuilder.Entity("TinyGenerator.Models.StoryStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AgentType")
                        .HasColumnType("TEXT");

                    b.Property<string>("CaptionToExecute")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("FunctionName")
                        .HasColumnType("TEXT");

                    b.Property<string>("OperationType")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<int>("Step")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("stories_status");
                });

            modelBuilder.Entity("TinyGenerator.Models.TaskTypeInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultCheckerRole")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultExecutorRole")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputMergeStrategy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<string>("ValidationCriteria")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("task_types");
                });

            modelBuilder.Entity("TinyGenerator.Models.TestDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AllowedPlugins")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecutionPlan")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpectedAsset")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpectedBehavior")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpectedPromptValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilesToCopy")
                        .HasColumnType("TEXT");

                    b.Property<string>("FunctionName")
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupName")
                        .HasColumnType("TEXT");

                    b.Property<string>("JsonResponseFormat")
                        .HasColumnType("TEXT");

                    b.Property<string>("Library")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Prompt")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Temperature")
                        .HasColumnType("REAL");

                    b.Property<string>("TestType")
                        .HasColumnType("TEXT");

                    b.Property<int>("TimeoutSecs")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("TopP")
                        .HasColumnType("REAL");

                    b.Property<string>("ValidScoreRange")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("test_definitions");
                });

            modelBuilder.Entity("TinyGenerator.Models.TtsVoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Age")
                        .HasColumnType("TEXT");

                    b.Property<string>("Archetype")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<string>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<double?>("Score")
                        .HasColumnType("REAL");

                    b.Property<string>("Tags")
                        .HasColumnType("TEXT");

                    b.Property<string>("TemplateWav")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("VoiceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("tts_voices");
                });
#pragma warning restore 612, 618
        }
    }
}
