-- INSERT statements per popolare la tabella test_definitions
-- Da aggiungere alla fine dello script recreate_all_tables.sql

-- ============================================================================
-- POPOLAMENTO test_definitions (42 record)
-- ============================================================================

INSERT INTO test_definitions VALUES(1,'base','text','ToUpper','Convert the word "test" to uppercase',NULL,NULL,0,1,1,25,'2025-11-11 18:10:09',NULL,'text',NULL,'functioncall','TEST','base_text.txt',NULL,NULL,0.0,0.0,NULL);
INSERT INTO test_definitions VALUES(2,'base','text','ToLower','Convert the word "TEST" to lowercase',NULL,NULL,0,2,1,25,'2025-11-11 18:10:09',NULL,'text',NULL,'functioncall','text','base_text.txt',NULL,NULL,0.0,0.0,NULL);
INSERT INTO test_definitions VALUES(3,'base','text','Trim','Remove leading and trailing spaces from the string "  test  "',NULL,NULL,0,3,1,25,'2025-11-11 18:10:09',NULL,'text',NULL,'functioncall','test','base_text.txt',NULL,NULL,0.0,0.0,NULL);
INSERT INTO test_definitions VALUES(4,'base','text','Length','Calculate the length of the string "test" using the text.length addin/function  and return only the value',NULL,NULL,0,4,1,25,'2025-11-11 18:10:09',NULL,'text',NULL,'functioncall','4','base_text.txt',NULL,NULL,0.0,0.0,NULL);
INSERT INTO test_definitions VALUES(5,'base','text','Substring','Extract the substring starting at position 1 with length 2 from the word "hello" using the text.substring addin/function  and return only the value',NULL,NULL,0,5,1,25,'2025-11-11 18:10:09',NULL,'text',NULL,'functioncall','he','base_text.txt',NULL,NULL,0.0,0.0,NULL);
INSERT INTO test_definitions VALUES(6,'base','text','Join','Join the elements ["a","b","c"] with separator "," using the text.join addin/function  and return only the value',NULL,NULL,0,6,1,25,'2025-11-11 18:10:09',NULL,'text',NULL,'functioncall','abc','base_text.txt',NULL,NULL,0.0,0.0,NULL);
INSERT INTO test_definitions VALUES(7,'base','text','Split','Split the string "a,b,c" using the text.split addin/function with separator ","',NULL,NULL,0,7,1,25,'2025-11-11 18:10:09',NULL,'text',NULL,'functioncall','a,b,c','base_text.txt',NULL,NULL,0.0,0.0,NULL);
INSERT INTO test_definitions VALUES(8,'base','math','Add','Calculate 2+2 using the add function of the math plugin, return only the value in plain text',NULL,NULL,0,8,1,25,'2025-11-11 18:10:09',NULL,'math',NULL,'functioncall','4','base_math.txt',NULL,NULL,0.0,0.0,NULL);
INSERT INTO test_definitions VALUES(9,'base','math','Subtract','Calculate 5-3 using the math.subtract addin/function , return only the value in plain text',NULL,NULL,0,9,1,25,'2025-11-11 18:10:09',NULL,'math',NULL,'functioncall','2','base_math.txt',NULL,NULL,0.0,0.0,NULL);
INSERT INTO test_definitions VALUES(10,'base','math','Multiply','Calculate 3*4 using the math.multiply addin/function, return only the value in plain text',NULL,NULL,0,10,1,25,'2025-11-11 18:10:09',NULL,'math',NULL,'functioncall','12','base_math.txt',NULL,NULL,0.0,0.0,NULL);
INSERT INTO test_definitions VALUES(11,'base','math','Divide','Calculate 8/2 using the math.divide addin/function, return only the value in plain text',NULL,NULL,0,11,1,25,'2025-11-11 18:10:09',NULL,'math',NULL,'functioncall','4','base_math.txt',NULL,NULL,0.0,0.0,NULL);
INSERT INTO test_definitions VALUES(12,'base','math','Sqrt','Calculate the square root of 9 using the math.sqrt addin/function  and return only the value',NULL,NULL,0,12,1,25,'2025-11-11 18:10:09',NULL,'math',NULL,'functioncall','3','base_math.txt',NULL,NULL,0.0,0.0,NULL);
INSERT INTO test_definitions VALUES(13,'base','time','Now','What time is it? Use the now function',NULL,NULL,0,13,1,25,'2025-11-11 18:10:09',NULL,'time',NULL,'functioncall',NULL,'base_time.txt',NULL,NULL,0.0,0.0,NULL);
INSERT INTO test_definitions VALUES(14,'base','time','Today','What is today''s date? Use today',NULL,NULL,0,14,1,25,'2025-11-11 18:10:09',NULL,'time',NULL,'functioncall',NULL,'base_time.txt',NULL,NULL,0.0,0.0,NULL);
INSERT INTO test_definitions VALUES(15,'base','time','AddDays','Add 2 days to the date 2025-01-01 using the time.adddays addin/function  and return only the value',NULL,NULL,0,15,1,25,'2025-11-11 18:10:09',NULL,'time',NULL,'functioncall','2025-01-03','base_time.txt',NULL,NULL,0.0,0.0,NULL);
INSERT INTO test_definitions VALUES(16,'base','time','AddHours','Add 3 hours to the time 10:00 using the time.addhours addin/function  and return only the value',NULL,NULL,0,16,1,25,'2025-11-11 18:10:09',NULL,'time',NULL,'functioncall','13:00','base_time.txt',NULL,NULL,0.0,0.0,NULL);
INSERT INTO test_definitions VALUES(17,'base','filesystem','FileExists','Check if the file /tmp/test.txt exists using the filesystem.file_exists addin/function and return true or false only',NULL,NULL,0,17,1,25,'2025-11-11 18:10:09',NULL,'filesystem',NULL,'functioncall','false','base_filesystem.txt',NULL,NULL,0.0,0.0,NULL);
INSERT INTO test_definitions VALUES(18,'base','filesystem','ReadAllText','Read the contents of the file /tmp/test.txt using the filesystem.read_all_text addin/function',NULL,NULL,0,18,1,25,'2025-11-11 18:10:09',NULL,'filesystem',NULL,'functioncall',NULL,'base_filesystem.txt',NULL,NULL,0.0,0.0,NULL);
INSERT INTO test_definitions VALUES(19,'base','http','HttpGetAsync','Make a GET request to https://example.com using the http.http_get addin/function',NULL,NULL,0,19,1,25,'2025-11-11 18:10:09',NULL,'http',NULL,'functioncall',NULL,'base_http.txt',NULL,NULL,0.0,0.0,NULL);
INSERT INTO test_definitions VALUES(20,'base','memory','RememberAsync','Remember the phrase "memory test value" in the collection "test_mem" using the memory.remember addin/function and return only the value',NULL,NULL,0,20,1,25,'2025-11-11 18:10:09',NULL,'memory',NULL,'functioncall','memory test value','base_memory.txt',NULL,NULL,0.0,0.0,NULL);
INSERT INTO test_definitions VALUES(21,'base','memory','RecallAsync','Retrieve the phrase from the collection "test_mem" using the memory.recall addin/function',NULL,NULL,0,21,1,25,'2025-11-11 18:10:09',NULL,'memory',NULL,'functioncall',NULL,'base_memory.txt',NULL,NULL,0.0,0.0,NULL);
INSERT INTO test_definitions VALUES(22,'base','memory','ForgetAsync','Forget the phrase from the collection "test_mem" using the memory.forget addin/function',NULL,NULL,0,22,1,25,'2025-11-11 18:10:09',NULL,'memory',NULL,'functioncall',NULL,'base_memory.txt',NULL,NULL,0.0,0.0,NULL);
INSERT INTO test_definitions VALUES(23,'tts','tts','tts_test',replace(replace('This is the story: Il ponte di comando dell'IDS Folgore era immerso in una luce blu soffusa quando il turno notturno venne interrotto da un brusco tremolio della struttura. I pannelli sul lato destro emisero una serie di bip d'allarme, e il Comandante Rinaldi alzò lo sguardo dallo schermo tattico.
«Che cosa diavolo è stato?» sbottò Rinaldi, tentando di mantenere la voce ferma.
La Tenente Serra, seduta alla console sensori, scorse rapidamente una serie di grafici. «Un impulso gravitazionale, signore. Proveniente dal Settore 14. Non è naturale… e non è nei nostri registri.»
Rinaldi fece una pausa, cercando di capire. Era da settimane che ricevevano segnali anomali da quella zona.
«Ortega!» chiamò.
Lo Specialista Ortega si precipitò alla console di diagnostica. «Sto controllando, Comandante. Ci sono fluttuazioni di campo che non riesco a identificare. Non sembrano emissioni note.»
Una breve pausa si abbatté sul ponte. Il rumore continuo delle ventole sembrava amplificato dal silenzio improvviso.
«Serra,» disse infine Rinaldi, «voglio una scansione approfondita. Gamma completa, e incrocia i dati con i registri dell'ultimo mese.»
La Tenente annuì, anche se il suo volto tradiva una certa preoccupazione. «Sì, signore. Avvio la procedura.»
Tornò a lampeggiare un segnale giallo sulla console di Ortega. «Comandante,» disse lo specialista, «ricevo un eco attivo. Non siamo soli.»
Rinaldi si irrigidì. «Origine?»
«Settore 14. E si avvicina.»
Un'altra pausa, più lunga. Serra guardò il Comandante, poi tornò ai sensori.
«Signore,» disse con voce tesa, «l'eco cambia frequenza. È come se ci stesse… scandagliando.»
Rinaldi inspirò profondamente. «Portate gli scudi al 40%. E mantenete la distanza. Non reagite finché non capiamo cosa abbiamo davanti.»
Ortega eseguì immediatamente, mentre Serra fissava lo schermo con crescente tensione.
«Comandante…» mormorò la Tenente. «Sta per inviare un segnale.»
Rinaldi chiuse gli occhi un istante. «Allora ascoltiamo.»','\r',char(13)),'\n',char(10)),NULL,NULL,0,3,1,300,'2025-11-11 18:10:09',NULL,'ttsschema',NULL,'tts',NULL,'test_tts2.txt',NULL,'tts_storia.txt',0.0,0.0,NULL);
INSERT INTO test_definitions VALUES(24,'tts','tts','ListVoicesAsync','List TTS voices using the tts.list_voices addin/function',NULL,NULL,0,1,0,30,'2025-11-11 18:10:09',NULL,'http,tts',NULL,'functioncall',NULL,NULL,NULL,NULL,0.0,0.0,NULL);
INSERT INTO test_definitions VALUES(25,'tts','tts','SynthesizeAsync','Synthesize a short text using the tts.synthesize addin/function',NULL,NULL,0,2,0,90,'2025-11-11 18:10:09',NULL,'http,tts',NULL,'functioncall',NULL,NULL,NULL,NULL,0.0,0.0,NULL);
INSERT INTO test_definitions VALUES(26,'music','audiocraft','CheckHealthAsync','Check if AudioCraft is online using the audiocraft.check_health addin/function','LastCalled == "CheckHealthAsync"',NULL,0,1,1,30,'2025-11-11 18:10:09',NULL,'audiocraft,http',NULL,'functioncall',NULL,NULL,NULL,NULL,0.7,0.9,NULL);
INSERT INTO test_definitions VALUES(27,'music','audiocraft','ListModelsAsync','List AudioCraft models using the audiocraft.list_models addin/function','LastCalled == "ListModelsAsync"',NULL,0,1,1,30,'2025-11-11 18:10:09',NULL,'audiocraft,http',NULL,'functioncall',NULL,NULL,NULL,NULL,0.7,0.9,NULL);
INSERT INTO test_definitions VALUES(28,'music','audiocraft','GenerateMusicAsync','Generate a short music snippet using the audiocraft.generate_music addin/function','LastCalled == "GenerateMusicAsync"','.wav',0,1,1,180,'2025-11-11 18:10:09',NULL,'audiocraft,http',NULL,'functioncall',NULL,NULL,NULL,NULL,0.7,0.9,NULL);
INSERT INTO test_definitions VALUES(29,'sound','audiocraft','GenerateSoundAsync','Generate a short sound effect using the audiocraft.generate_sound addin/function','LastCalled == "GenerateSoundAsync"','.wav',0,1,1,180,'2025-11-11 18:10:09',NULL,'audiocraft,http',NULL,'functioncall',NULL,NULL,NULL,NULL,0.7,0.9,NULL);
INSERT INTO test_definitions VALUES(30,'sound','audiocraft','DownloadFile','Download a sample file using the audiocraft.download_file addin/function','LastCalled == "DownloadFile"',NULL,0,1,1,60,'2025-11-11 18:10:09',NULL,'audiocraft,http',NULL,'functioncall',NULL,NULL,NULL,NULL,0.7,0.9,NULL);
INSERT INTO test_definitions VALUES(31,'writer','StoryWriterSkill','CreateStory',replace(replace('Scrivi una storia estesa di fantascienza in stile moderno, con dialoghi in italiano e azione. Il personaggio principale è il capitano Carta della nave spaziale Cavour.

**Requisiti:**

* La storia deve essere lunga almeno 50.000 caratteri
* Deve avere un finale epico e coinvolgente
* I personaggi devono essere ben sviluppati e con motivazioni plausibili
* La trama deve essere complessa e full di rivoli

**Libertà creativa:**

Sii libero di creare la tua storia in stile moderno, con le tue idee e le tue visioni. Non ci sono limitazioni sulla lunghezza o sulla complessità della storia.
','\r',char(13)),'\n',char(10)),NULL,NULL,0,1,0,6000,'2025-11-11 18:10:09',NULL,'memory',NULL,'writer',NULL,'writer_long_step_story.txt',NULL,NULL,1.5,0.9,NULL);
INSERT INTO test_definitions VALUES(32,'texteval','coerenza_narrativa','Coerenza narrativa',replace(replace('Valuta il seguente testo concentrandoti sulla COERENZA NARRATIVA. Devi identificare eventuali contraddizioni interne, eventi impossibili o incoerenze logiche. Restituisci SOLO un valore da 1 a 10 in testo semplice, con al massimo 2 caratteri. Non aggiungere altro. Non essere generoso con la valutazione.

Luca avanzò nel corridoio buio della nave abbandonata. La sua torcia tremolava, ma riuscì comunque a intravedere la porta blindata in fondo. «È chiusa dall'interno», mormorò, e si chinò per ascoltare eventuali rumori. Qualche istante dopo, però, spinse la porta e questa si aprì senza alcuna resistenza, spalancandosi come se fosse rimasta socchiusa per anni. All''interno trovò un diario che descriveva gli ultimi minuti dell'equipaggio. L'ultima pagina indicava chiaramente che tutti i membri erano fuggiti con le scialuppe. «Nessun superstite», concluse Luca. Un secondo dopo, una figura umana emerse da dietro un contenitore e gridò: «Ti stavo aspettando! Sono l'ultimo della squadra!». «Ma il diario diceva che erano scappati tutti», disse Luca. «Sì», rispose l'uomo. «In effetti sono scappati tutti. Anch'io. Da un'altra parte. Credo.»','\r',char(13)),'\n',char(10)),NULL,NULL,0,100,1,60,'2025-11-13 07:00:46',NULL,NULL,'1-3','question',NULL,NULL,'evaluation_1_10.json',NULL,0.7,0.9,NULL);
INSERT INTO test_definitions VALUES(33,'texteval','struttura','Struttura',replace(replace('Valuta il seguente testo concentrandoti sulla STRUTTURA. Devi rilevare l''assenza di conflitto, l''assenza di sviluppo e una conclusione mancante. Restituisci il punteggio da 1 a 10  in testo semplice, con al massimo 2 caratteri, non aggiungere altro. Non essere generoso con la valutazione.

Maria camminava sulla spiaggia al mattino presto. Il cielo era limpido, l'acqua immobile e nessuno in giro. Raccolse una conchiglia e la osservò. Poi ne trovò un'altra, più grande, e la mise nello zaino. Proseguì lungo la riva, ascoltando solo il rumore delle onde tranquille. Arrivò al molo, si sedette e guardò l'orizzonte. Pensò a quanto fosse bello quel posto e decise che sarebbe tornata il giorno dopo. Si alzò e ricominciò a camminare.','\r',char(13)),'\n',char(10)),NULL,NULL,0,100,1,60,'2025-11-13 07:00:46',NULL,NULL,'1-3','question',NULL,NULL,'evaluation_1_10.json',NULL,0.7,0.9,NULL);
INSERT INTO test_definitions VALUES(34,'texteval','caratterizzazione_personaggi','Caratterizzazione',replace(replace('Valuta la CARATTERIZZAZIONE DEI PERSONAGGI. Devi verificare se i personaggi hanno voce propria, motivazioni e stile coerente, oppure se parlano tutti allo stesso modo. Restituisci il punteggio da 1 a 10  in testo semplice, con al massimo 2 caratteri, non aggiungere altro.

«Andiamo», disse Carlo. «Sì, andiamo», rispose Marco. «Anche secondo me dobbiamo andare», aggiunse Elisa. I tre percorsero il sentiero alberato. «Quando arriviamo?», chiese Marco. «Presto», disse Carlo. «Sì, presto», ripeté Elisa. La foresta era silenziosa. I tre continuavano a camminare senza mostrare alcuna emozione e parlando sempre allo stesso modo.','\r',char(13)),'\n',char(10)),NULL,NULL,0,100,1,60,'2025-11-13 07:00:46',NULL,NULL,'1-4','question',NULL,NULL,'evaluation_1_10.json',NULL,0.7,0.9,NULL);
INSERT INTO test_definitions VALUES(35,'texteval','dialoghi','Dialoghi',replace(replace('Valuta la qualità dei DIALOGHI. Devi rilevare dialoghi finti, innaturali, inutili o che non fanno avanzare la scena. Restituisci solo il punteggio da 1 a 10 in testo semplice, con al massimo 2 caratteri, non aggiungere altro.

«Buongiorno, Giovanni.» «Buongiorno, Anna. È mattina, quindi ti dico buongiorno.» «Apprezzo che tu abbia notato che è mattina.» «Prego. Adesso ti dico che ho bevuto un caffè.» «Interessante. Io ho mangiato una mela.» «Questa informazione è utile.» «Certo. Cosa facciamo ora?» «Forse possiamo parlare ancora delle nostre abitudini quotidiane.»','\r',char(13)),'\n',char(10)),NULL,NULL,0,100,1,60,'2025-11-13 07:00:46',NULL,NULL,'1-3','question',NULL,NULL,'evaluation_1_10.json',NULL,0.7,0.9,NULL);
INSERT INTO test_definitions VALUES(36,'texteval','ritmo','Ritmo',replace(replace('Valuta il RITMO narrativo. Devi rilevare rallentamenti eccessivi, descrizioni inutili e mancanza di dinamica. Rispondi con il punteggio da 1 a 10, con al massimo 2 caratteri, non aggiungere altro.

Il comandante aprì il cassetto. Il cassetto era di legno. Il legno era marrone scuro, con venature lucide che ricordavano la corteccia di un albero di montagna. L'interno del cassetto era rivestito di stoffa rossa, con un odore leggermente polveroso. Si chinò lentamente, inspirando l'odore della stoffa, poi allungò la mano osservando ogni millimetro del movimento. La luce filtrava dalla finestra con un'angolazione di quarantacinque gradi.','\r',char(13)),'\n',char(10)),NULL,NULL,0,100,1,60,'2025-11-13 07:00:46',NULL,NULL,'2-4','question',NULL,NULL,'evaluation_1_10.json',NULL,0.7,0.9,NULL);
INSERT INTO test_definitions VALUES(37,'texteval','originalita','Originalità 1',replace(replace('Valuta l''ORIGINALITÀ della storia. Devi identificare cliché, formule narrative abusate o mancanza di idee originali. Rispondi con la valutazione da 1 a 10 in testo semplice, con al massimo 2 caratteri, non aggiungere altro.

Il giovane prescelto, che non sapeva di essere speciale, viveva in un villaggio isolato. Un vecchio misterioso lo raggiunse una sera e gli disse: «Tu sei l'unico che può salvare il mondo». Il ragazzo, incredulo, accettò subito la missione.','\r',char(13)),'\n',char(10)),NULL,NULL,0,100,1,60,'2025-11-13 07:00:46',NULL,NULL,'1-3','question',NULL,NULL,'evaluation_1_10.json',NULL,0.7,0.9,NULL);
INSERT INTO test_definitions VALUES(38,'texteval','stile','Stile 1',replace(replace('Valuta lo STILE del testo. Devi rilevare frasi ripetitive, monotone o struttura sempre identica. Rispondi solo con il voto da 1 a 10, con al massimo 2 caratteri, non aggiungere altro.

Il sole era alto nel cielo. Il vento soffiava leggero. Le onde si muovevano lentamente. Il capitano guardava il mare. La nave procedeva dritta. Il cielo era limpido.','\r',char(13)),'\n',char(10)),NULL,NULL,0,100,1,60,'2025-11-13 07:00:46',NULL,NULL,'1-4','question',NULL,NULL,'evaluation_1_10.json',NULL,0.7,0.9,NULL);
INSERT INTO test_definitions VALUES(39,'texteval','worldbuilding','Worldbuilding 1',replace(replace('Valuta il WORLDBUILDING. Devi rilevare incoerenze nel mondo, regole non rispettate o impossibili. Rispondi solo con la valutazione da 1 a 10, con al massimo 2 caratteri, non aggiungere altro.

Nel pianeta di Farsis non esisteva ossigeno da milioni di anni, eppure gli abitanti umani respiravano senza problemi. Le foreste erano composte da alberi di ghiaccio puro che però bruciavano spontaneamente. La capitale si trovava nel deserto, ma era descritta come immersa in una foresta tropicale fitta e umida.','\r',char(13)),'\n',char(10)),NULL,NULL,0,100,1,60,'2025-11-13 07:00:46',NULL,NULL,'1-3','question',NULL,NULL,'evaluation_1_10.json',NULL,0.7,0.9,NULL);
INSERT INTO test_definitions VALUES(40,'texteval','coerenza_tematica','Coerenza tematica 1',replace(replace('Valuta la COERENZA TEMATICA. Devi verificare che il tono, il tema e il genere siano consistenti. Rispondi solo con la valutazione da 1 a 10, con al massimo 2 caratteri, non aggiungere altro

La storia iniziò come un racconto horror ambientato in una villa abbandonata. Tuttavia, dopo poche righe, i personaggi decisero di organizzare una festa in maschera con musica allegra. Poi la narrazione cambiò ancora e diventò un manuale di giardinaggio.','\r',char(13)),'\n',char(10)),NULL,NULL,0,100,1,60,'2025-11-13 07:00:46',NULL,NULL,'1-3','question',NULL,NULL,'evaluation_1_10.json',NULL,0.7,0.9,NULL);
INSERT INTO test_definitions VALUES(41,'texteval','impatto_emotivo','Impatto emotivo 1',replace(replace('Valuta l''IMPATTO EMOTIVO. Devi rilevare se la scena trasmette emozioni adeguate alla situazione. Rispondi solo con la valutazione da 1 a 10, con al massimo 2 caratteri, non aggiungere altro.

Il soldato vide l'esplosione. Pensò che fosse un evento rilevante. Si voltò e osservò il fumo. Poi decise di tornare nella tenda perché era ora di riposare. Non provò nulla di particolare.','\r',char(13)),'\n',char(10)),NULL,NULL,0,100,1,60,'2025-11-13 07:00:46',NULL,NULL,'1-3','question',NULL,NULL,'evaluation_1_10.json',NULL,0.7,0.9,NULL);
INSERT INTO test_definitions VALUES(42,'writer','writer','writer','Make a long modern story in italian language, with action, with at least 60000 characters. Return the title and the full story only.',NULL,NULL,0,2,1,0,'2025-11-29 19:23:56',NULL,NULL,NULL,'writer',NULL,NULL,NULL,NULL,1.2,0.5,NULL);
