using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TinyGenerator.Models
{
    [Table("stories")]
    public class StoryRecord
    {
        [Column("id")]
        public long Id { get; set; }

        [Column("story_id")]
        public long? StoryId { get; set; }
        
        [Column("generation_id")]
        public string GenerationId { get; set; } = string.Empty;
        
        [Column("memory_key")]
        public string MemoryKey { get; set; } = string.Empty;
        
        [Column("ts")]
        public string Timestamp { get; set; } = string.Empty;
        
        [Column("prompt")]
        public string Prompt { get; set; } = string.Empty;
        
        [Column("title")]
        public string? Title { get; set; }
        
        [Column("story_raw")]
        public string StoryRaw { get; set; } = string.Empty;

        [Column("story_revised")]
        public string? StoryRevised { get; set; }

        [Column("story_tagged")]
        public string? StoryTagged { get; set; }

        [Column("story_tagged_version")]
        public int? StoryTaggedVersion { get; set; }

        [Column("story_rows")]
        public string? StoryRows { get; set; }

        [Column("story_tags")]
        public string? StoryTags { get; set; }

        [Column("formatter_model")]
        public int? FormatterModelId { get; set; }

        [Column("formatter_prompt_hash")]
        public string? FormatterPromptHash { get; set; }
        
        [Column("char_count")]
        public int CharCount { get; set; }
        
        [NotMapped]
        public string Model { get; set; } = string.Empty;
        
        [NotMapped]
        public string Agent { get; set; } = string.Empty;
        
        [Column("eval")]
        public string Eval { get; set; } = string.Empty;
        
        [Column("score")]
        public double Score { get; set; }
        
        [Column("approved")]
        public bool Approved { get; set; }

        [Column("deleted")]
        public bool Deleted { get; set; }
        
        [NotMapped]
        public string Status { get; set; } = string.Empty;
        
        [Column("status_id")]
        public int? StatusId { get; set; }
        
        [NotMapped]
        public string? StatusDescription { get; set; }
        
        [NotMapped]
        public string? StatusColor { get; set; }
        
        [NotMapped]
        public string? StatusOperationType { get; set; }
        
        [NotMapped]
        public string? StatusAgentType { get; set; }
        
        [NotMapped]
        public string? StatusFunctionName { get; set; }
        
        [NotMapped]
        public int? StatusStep { get; set; }
        
        [Column("folder")]
        public string? Folder { get; set; }
        
        [NotMapped]
        public bool HasVoiceSource { get; set; }

        // Generated asset flags
        [Column("generated_tts_json")]
        public bool GeneratedTtsJson { get; set; }

        [Column("generated_tts")]
        public bool GeneratedTts { get; set; }

        [Column("generated_ambient")]
        public bool GeneratedAmbient { get; set; }

        [Column("generated_music")]
        public bool GeneratedMusic { get; set; }

        [Column("generated_effects")]
        public bool GeneratedEffects { get; set; }

        [Column("generated_mixed_audio")]
        public bool GeneratedMixedAudio { get; set; }

        /// <summary>
        /// Indicates if the story has a final mixed audio file (final_mix.wav or final_mix.mp3)
        /// </summary>
        [NotMapped]
        public bool HasFinalMix { get; set; }

        // Test information (if story was generated from a test)
        [NotMapped]
        public int? TestRunId { get; set; }
        
        [NotMapped]
        public int? TestStepId { get; set; }
        
        [Column("model_id")]
        public int? ModelId { get; set; }
        
        [Column("agent_id")]
        public int? AgentId { get; set; }

        /// <summary>
        /// Optional foreign key to Series table. Indicates which series this story belongs to.
        /// </summary>
        [Column("serie_id")]
        public int? SerieId { get; set; }

        /// <summary>
        /// Episode number within the series (1-based). Only meaningful if SerieId is not null.
        /// </summary>
        [Column("serie_episode")]
        public int? SerieEpisode { get; set; }

        [NotMapped]
        public string? SerieName { get; set; }

        /// <summary>
        /// Short summary of the story (3-5 sentences), generated by a summarizer agent after story completion.
        /// </summary>
        [Column("summary")]
        public string? Summary { get; set; }

        /// <summary>
        /// JSON string containing the list of characters with their canonical names and genders.
        /// Format: [{"name": "Carta", "gender": "male", "role": "protagonist", "aliases": ["COMANDANTE CARTA", "Alessandro Carta"]}]
        /// </summary>
        [Column("characters")]
        public string? Characters { get; set; }

        /// <summary>
        /// JSON string containing the narrative structure generated by the planner agent.
        /// Format: Array of beat definitions with Save the Cat structure (15 beats).
        /// </summary>
        [Column("story_structure")]
        public string? StoryStructure { get; set; }

        /// <summary>
        /// Planner mode for this story: Off / Assist / Auto.
        /// Stored as text to keep it DB-friendly and easily editable.
        /// </summary>
        [Column("planner_mode")]
        public string? PlannerMode { get; set; }

        // Narrative Engine extensions
        [Column("narrative_profile_id")]
        public int? NarrativeProfileId { get; set; }

        [Column("runtime_state_id")]
        public long? RuntimeStateId { get; set; }

        [Column("narrative_status")]
        public string? NarrativeEngineStatus { get; set; }

        // Evaluations attached to the story (one for each saved evaluation)
        [NotMapped]
        public List<StoryEvaluation> Evaluations { get; set; } = new List<StoryEvaluation>();
        
        // Legacy properties for backward compatibility (mapped to Story field)
        [Obsolete("Use StoryRaw property instead")]
        [NotMapped]
        public string Story { get => StoryRaw; set => StoryRaw = value; }
        [Obsolete("Use StoryRaw property instead")]
        [NotMapped]
        public string StoryA { get => StoryRaw; set => StoryRaw = value; }
        [Obsolete("Use Model property instead")]
        [NotMapped]
        public string ModelA { get => Model; set => Model = value; }
        [Obsolete("Use Eval property instead")]
        [NotMapped]
        public string EvalA { get => Eval; set => Eval = value; }
        [Obsolete("Use Score property instead")]
        [NotMapped]
        public double ScoreA { get => Score; set => Score = value; }
        
        // Concurrency token for optimistic locking
        [Timestamp]
        public byte[]? RowVersion { get; set; }
    }
}
